#!/bin/bash



[[ "$TRACE" ]] && set -x


cat <<EOF >~/.aws/credentials
[default]
aws_access_key_id=${ACCESS_KEY}
aws_secret_access_key=${SECRET_KEY}
EOF

cat <<EOF >~/.aws/config
[default]
region=us-east-1
output=json
EOF

function error_exit {
	echo "${1:-"Unknown Error"}" 1>&2
	exit 1
}

LOCAL=$LOCAL_PATH
REMOTE=$S3_PATH

function restore {
  if [ "$(ls -A $LOCAL)" ]; then
		if [[ ${FORCE_RESTORE:false} == 'true' ]]; then
    	error_exit "local directory is not empty"
		fi
  fi

  echo "restoring $REMOTE => $LOCAL"
  if ! aws s3 sync "$REMOTE" "$LOCAL"; then
    error_exit "restore failed"
  fi
}

function backup {
  echo "backup $LOCAL => $REMOTE"
  if ! aws s3 sync "$LOCAL" "$REMOTE"; then
    echo "backup failed" 1>&2
    return 1
  fi
}

function final_backup {
  echo "backup $LOCAL => $REMOTE"
  while ! aws s3 sync "$LOCAL" "$REMOTE"; do
    echo "backup failed" 1>&2
    sleep 1
  done
  exit 0
}

function idle {
  echo "ready"
  while true; do
    sleep 42 &
    wait $!
  done
}

restore

trap final_backup SIGHUP SIGINT SIGTERM
trap "backup; idle" USR1

idle
